language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf libpam0g-dev autotools-dev cgroup-lite
  - gem install rake
script:
  - rake
